### ISSUE TITLE
Help!? 

### ISSUE THREAD

**Issue by ghost** [aieuo/if_plugin#2]
What this plugin does

**Comment by champmq** [comment]
I don't know the owner isn't answering

**Comment by aieuo** [comment]
You can construct logic to change the processing to be executed depending on the condition in the game like if statement.

example)
![スクリーンショット (170)](https://user-images.githubusercontent.com/35859665/57137291-640f2600-6dea-11e9-9b6b-3d2c474c952a.png)
![スクリーンショット (171)](https://user-images.githubusercontent.com/35859665/57137294-683b4380-6dea-11e9-808d-0c50031cc8cc.png)
When you touch the block you set, you will receive "You have over $ 1000" when you have $ 1000 or more, and "You do not have $ 1000" otherwise.

**Comment by DenielWorld** [comment]
Simplier in-game coding?

**Comment by champmq** [comment]
I would love the plugin if it would bei in english

**Comment by aieuo** [comment]
> Simplier in-game coding?
yes, like that



> I would love the plugin if it would bei in english
thanks!
